# Generated by Django 3.2.3 on 2021-07-30 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100, null=True)),
                ('LoginCode', models.CharField(max_length=100, null=True)),
                ('BuildingType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('AddressLine1', models.TextField(max_length=100, null=True)),
                ('AddressLine2', models.TextField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Province', models.CharField(max_length=100, null=True)),
                ('PostalCode', models.CharField(max_length=100, null=True)),
                ('BuildingStatus', models.PositiveSmallIntegerField(default=1, null=True)),
                ('InsDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ModDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('NoOfUsers', models.PositiveSmallIntegerField(default=1, null=True)),
                ('LicenseType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('ContactPerson', models.CharField(max_length=100, null=True)),
                ('ContactPersonCell', models.CharField(max_length=100, null=True)),
                ('ContactPersonEmail', models.CharField(max_length=100, null=True)),
                ('HasMonthlyMaintenance', models.BooleanField(null=True)),
                ('MaintenanceType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('MaintenancePM', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LevelName', models.CharField(max_length=100, null=True)),
                ('LevelType', models.PositiveSmallIntegerField(null=True)),
                ('IsActive', models.BooleanField(null=True)),
                ('InsDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ModDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('IsExpenseApplicable', models.BooleanField(null=True)),
                ('buildings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsite.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitName', models.CharField(max_length=200, null=True)),
                ('OccupiedStatus', models.PositiveSmallIntegerField(default=1, null=True)),
                ('UnitType', models.PositiveSmallIntegerField(default=1, null=True)),
                ('OwnedByMemberId', models.PositiveIntegerField(null=True)),
                ('OccupiedByMemberId', models.PositiveIntegerField(null=True)),
                ('CoveredArea', models.CharField(max_length=200, null=True)),
                ('IsDisputed', models.BooleanField(null=True)),
                ('DisputeDesc', models.TextField()),
                ('IsMaintenanceApplicable', models.BooleanField(null=True)),
                ('CurrentMaintenancePM', models.DecimalField(decimal_places=6, max_digits=30, null=True)),
                ('IsBLExpenseApplicable', models.BooleanField(null=True)),
                ('IsDLExpenseApplicable', models.BooleanField(null=True)),
                ('IsULExpenseApplicable', models.BooleanField(null=True)),
                ('buildings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsite.buildings')),
                ('levels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsite.levels')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberType', models.PositiveSmallIntegerField(null=True)),
                ('OwnerType', models.PositiveSmallIntegerField(null=True)),
                ('OccupantType', models.PositiveSmallIntegerField(null=True)),
                ('MemberName', models.CharField(max_length=100, null=True)),
                ('IsActive', models.BooleanField(null=True)),
                ('InsDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('ModDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('CellPhone', models.CharField(max_length=100, null=True)),
                ('Email', models.EmailField(max_length=100, null=True)),
                ('AddressLine1', models.TextField(max_length=100, null=True)),
                ('AddressLine2', models.TextField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Province', models.CharField(max_length=100, null=True)),
                ('PostalCode', models.CharField(max_length=100, null=True)),
                ('buildings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsite.buildings')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoginName', models.CharField(max_length=100, null=True)),
                ('LoginPassword', models.CharField(max_length=100, null=True)),
                ('FirstName', models.CharField(max_length=100, null=True)),
                ('LastName', models.CharField(max_length=100, null=True)),
                ('UserType', models.PositiveSmallIntegerField(null=True)),
                ('IsActive', models.BooleanField(null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('buildings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appsite.buildings')),
            ],
        ),
    ]
