# Generated by Django 3.2.5 on 2021-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0003_alter_buildingusers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='IsActive',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='levels',
            name='LevelType',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Ground', 'Ground'), ('Mezanine', 'Mezanine'), ('Floor', 'Floor')], max_length=200, null=True),
        ),
    ]
